language:
- node_js
node_js:
- '8'
jobs:
  include:
    - stage: test
      if: |
        type = pull_request
      script: yarn test
    - stage: build
      if: |
        type = push
      script: yarn build
