stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: (type = push) AND (branch = master)
language:
- node_js
node_js:
- '8'
env:
  - CI: false
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: deploy
      script: yarn build
